### ISSUE TITLE
How do I run this network with my own data?

### ISSUE THREAD

**Issue by mostafa501** [weiguangzhao/PBNet#3]
Congrats on the release and thank you for open sourcing your code!
I would love to know if you have any plans to open-source the inference code used on our own data. Currently, it seems that only the train/test code is available, and would love to use a python interface to use this method with some different point clouds.
Any help on this would be very much appreciated. Thank you for the contribution !!

**Comment by weiguangzhao** [comment]
Thanks for your attention. We currently have no plans to provide a framework to accommodate personalized data because our method is based on semantic segmentation, and retraining is necessary for open categories.  You may consider using our code to retrain your data. For this code, xyz, semantic label, instance label is necessary, and rgb, face is optional. Your also need to refine the hyperparameter radius and density for your data. 

At least, sorry for the delayed response; I've been struggling with cvpr.  If you have any questions, feel free to consult with me at any time
